[package]
name = "custom_debug"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["extra-traits", "visit"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
log = "0.4.27"